### ISSUE TITLE
Arrumar a responsividade 

### ISSUE THREAD

**Issue by R-enanVieira** [Luidooo/MoneyTables#1]
O site está quebrando quando o zoom é aumentado ou dimininuído. Os buttons não acompanham os campos de texto

![Captura de tela de 2024-07-02 17-37-22](https://github.com/Luidooo/MoneyTables/assets/65179736/3bd09912-8422-45c8-82c2-e74dd95d43ca)

![Captura de tela de 2024-07-02 17-37-29](https://github.com/Luidooo/MoneyTables/assets/65179736/2477938c-2cf9-48bb-a692-55389f769c0c)

**Comment by R-enanVieira** [comment]
![diagrama_api_rest](https://github.com/user-attachments/assets/6f453006-823d-4c16-90b9-e0f76074b811)

**Comment by Luidooo** [comment]
![image](https://github.com/user-attachments/assets/5e691ac0-87ed-488b-be35-29cf3369f38b)
